"""empty message

Revision ID: 244b9f592fef
Revises: 71f004b817b9
Create Date: 2024-05-09 16:40:41.511067

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '244b9f592fef'
down_revision = '71f004b817b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_templates',
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('sensitivity', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('plume_form', sa.String(), nullable=False),
    sa.Column('angle_width', sa.Float(), nullable=True),
    sa.Column('angle_height', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('spot_width', sa.Float(), nullable=True),
    sa.Column('spot_height', sa.Float(), nullable=True),
    sa.Column('min_plume_size', sa.Float(), nullable=True),
    sa.Column('distance_for_plume_size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('template_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_templates')
    # ### end Alembic commands ###
