"""empty message

Revision ID: 31577dc4ce53
Revises: bf89710ef760
Create Date: 2024-05-21 23:32:38.861613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '31577dc4ce53'
down_revision = 'bf89710ef760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_calculation_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_calculation_templates', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
