"""empty message

Revision ID: 569c8756bf09
Revises: 5b6a5813e2bb
Create Date: 2024-05-26 19:00:07.588057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569c8756bf09'
down_revision = '5b6a5813e2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_calculation_templates', schema=None) as batch_op:
        batch_op.drop_constraint('saved_calculation_templates_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_calculation_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint('saved_calculation_templates_title_key', ['title'])

    # ### end Alembic commands ###
