"""empty message

Revision ID: 6fc047f5cfab
Revises: 244b9f592fef
Create Date: 2024-05-11 15:30:07.237632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc047f5cfab'
down_revision = '244b9f592fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_calculation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sensitivity', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('plume_form', sa.String(), nullable=False),
    sa.Column('angle_width', sa.Float(), nullable=True),
    sa.Column('angle_height', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('spot_width', sa.Float(), nullable=True),
    sa.Column('spot_height', sa.Float(), nullable=True),
    sa.Column('min_plume_size', sa.Float(), nullable=True),
    sa.Column('distance_for_plume_size', sa.Float(), nullable=True),
    sa.Column('max_distance', sa.Float(), nullable=False),
    sa.Column('min_distance', sa.Float(), nullable=True),
    sa.Column('plume_width_module3', sa.Float(), nullable=True),
    sa.Column('plume_height_module3', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_calculation_templates')
    # ### end Alembic commands ###
