"""empty message

Revision ID: bf89710ef760
Revises: e07ccf757b41
Create Date: 2024-05-20 12:07:12.478235

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bf89710ef760'
down_revision = 'e07ccf757b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_calculation_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculator_type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_calculation_templates', schema=None) as batch_op:
        batch_op.drop_column('calculator_type')

    # ### end Alembic commands ###
